name: Dynamic Remote Flutter Build & Deploy

on:
  repository_dispatch:
    types: [trigger-build]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.client_payload.source_repo }}
          ref: ${{ github.event.client_payload.ref }}
          token: ${{ secrets.GH_PAT }}
          path: source_code

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Build Web
        run: |
          cd source_code
          flutter pub get
          flutter build web --release

      - name: Deploy to Target Repo
        uses: JamesIves/github-pages-deploy-action@v4.7.2
        with:
          token: ${{ secrets.GH_PAT }}
          branch: gh-pages
          folder: source_code/build/web
          repository-name: ${{ github.event.client_payload.target_repo }}
          clean: true
          commit-message: "Deploy from ${{ github.event.client_payload.source_repo }}@${{ github.event.client_payload.sha }}"
